"""Initial schema: the tables of docs/DATA_MODEL.md (see app/models.py).

Autogenerated from the models, then reviewed.

Revision ID: 0001
Revises: 
Create Date: 2026-09-21 21:05:07.022939
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('matches',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), server_default='', nullable=False),
    sa.Column('players', sa.SmallInteger(), nullable=False),
    sa.Column('red_fives', sa.Boolean(), nullable=False),
    sa.Column('length', sa.Text(), nullable=False),
    sa.Column('starting_points', sa.Integer(), nullable=False),
    sa.Column('return_score', sa.Integer(), nullable=False),
    sa.Column('uma', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('end_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_level', sa.Text(), nullable=True),
    sa.Column('max_level_rank', sa.SmallInteger(), sa.Computed("CASE WHEN max_level IS NULL THEN NULL ELSE (CASE max_level WHEN 'sinNombre' THEN 0 WHEN 'mangan' THEN 1 WHEN 'haneman' THEN 2 WHEN 'baiman' THEN 3 WHEN 'sanbaiman' THEN 4 WHEN 'kazoeYakuman' THEN 5 WHEN 'yakuman' THEN 6 WHEN 'dobleYakuman' THEN 7 WHEN 'tripleYakuman' THEN 8 ELSE 6 END) END", persisted=True), nullable=True),
    sa.Column('is_test', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.CheckConstraint("end_reason IS NULL OR end_reason IN ('final_round', 'bust', 'manual')", name=op.f('ck_matches_end_reason')),
    sa.CheckConstraint("length IN ('east', 'south')", name=op.f('ck_matches_length')),
    sa.CheckConstraint("status IN ('in_progress', 'finished', 'abandoned')", name=op.f('ck_matches_status')),
    sa.CheckConstraint('players IN (3, 4)', name=op.f('ck_matches_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_index(op.f('ix_matches_max_level_rank'), 'matches', ['max_level_rank'], unique=False)
    op.create_index(op.f('ix_matches_started_at'), 'matches', ['started_at'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('slug', name=op.f('uq_players_slug'))
    )
    op.create_table('adjustments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Text(), nullable=False),
    sa.Column('client_uuid', sa.Text(), nullable=False),
    sa.Column('after_seq', sa.SmallInteger(), nullable=False),
    sa.Column('seat', sa.SmallInteger(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_adjustments_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adjustments')),
    sa.UniqueConstraint('client_uuid', name=op.f('uq_adjustments_client_uuid'))
    )
    op.create_index(op.f('ix_adjustments_match_id'), 'adjustments', ['match_id'], unique=False)
    op.create_table('hands',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Text(), nullable=False),
    sa.Column('seq', sa.SmallInteger(), nullable=False),
    sa.Column('round_wind', sa.Text(), nullable=False),
    sa.Column('round_number', sa.SmallInteger(), nullable=False),
    sa.Column('honba', sa.SmallInteger(), nullable=False),
    sa.Column('riichi_pot_before', sa.SmallInteger(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('abortive_reason', sa.Text(), nullable=True),
    sa.Column('deal_in_seat', sa.SmallInteger(), nullable=True),
    sa.Column('score_delta', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('client_uuid', sa.Text(), nullable=False),
    sa.CheckConstraint("outcome IN ('tsumo', 'ron', 'exhaustive_draw', 'abortive_draw', 'nagashi_mangan', 'chombo')", name=op.f('ck_hands_outcome')),
    sa.CheckConstraint("round_wind IN ('este', 'sur', 'oeste', 'norte')", name=op.f('ck_hands_round_wind')),
    sa.CheckConstraint('cardinality(score_delta) IN (3, 4)', name=op.f('ck_hands_score_delta')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_hands_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hands')),
    sa.UniqueConstraint('client_uuid', name=op.f('uq_hands_client_uuid')),
    sa.UniqueConstraint('match_id', 'seq', name=op.f('uq_hands_match_id_seq'))
    )
    op.create_index(op.f('ix_hands_deal_in_seat'), 'hands', ['deal_in_seat'], unique=False)
    op.create_table('match_players',
    sa.Column('match_id', sa.Text(), nullable=False),
    sa.Column('seat', sa.SmallInteger(), nullable=False),
    sa.Column('player_id', sa.Text(), nullable=True),
    sa.Column('guest_name', sa.Text(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('placement', sa.SmallInteger(), nullable=True),
    sa.Column('uma_points', sa.Float(), nullable=True),
    sa.CheckConstraint('player_id IS NOT NULL OR guest_name IS NOT NULL', name=op.f('ck_match_players_who')),
    sa.CheckConstraint('seat BETWEEN 0 AND 3', name=op.f('ck_match_players_seat')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_players_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_match_players_player_id_players')),
    sa.PrimaryKeyConstraint('match_id', 'seat', name=op.f('pk_match_players'))
    )
    op.create_index(op.f('ix_match_players_player_id'), 'match_players', ['player_id'], unique=False)
    op.create_table('hand_riichi',
    sa.Column('hand_id', sa.BigInteger(), nullable=False),
    sa.Column('seat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], name=op.f('fk_hand_riichi_hand_id_hands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hand_id', 'seat', name=op.f('pk_hand_riichi'))
    )
    op.create_table('hand_tenpai',
    sa.Column('hand_id', sa.BigInteger(), nullable=False),
    sa.Column('seat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], name=op.f('fk_hand_tenpai_hand_id_hands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hand_id', 'seat', name=op.f('pk_hand_tenpai'))
    )
    op.create_table('hand_wins',
    sa.Column('hand_id', sa.BigInteger(), nullable=False),
    sa.Column('winner_seat', sa.SmallInteger(), nullable=False),
    sa.Column('han', sa.SmallInteger(), nullable=True),
    sa.Column('fu', sa.SmallInteger(), nullable=True),
    sa.Column('level', sa.Text(), nullable=True),
    sa.Column('level_rank', sa.SmallInteger(), sa.Computed("CASE WHEN level IS NULL THEN NULL ELSE (CASE level WHEN 'sinNombre' THEN 0 WHEN 'mangan' THEN 1 WHEN 'haneman' THEN 2 WHEN 'baiman' THEN 3 WHEN 'sanbaiman' THEN 4 WHEN 'kazoeYakuman' THEN 5 WHEN 'yakuman' THEN 6 WHEN 'dobleYakuman' THEN 7 WHEN 'tripleYakuman' THEN 8 ELSE 6 END) END", persisted=True), nullable=True),
    sa.Column('base_points', sa.Integer(), nullable=True),
    sa.Column('points_won', sa.Integer(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('winner_open', sa.Boolean(), nullable=True),
    sa.Column('hand_tiles', sa.Text(), nullable=True),
    sa.Column('situation_flags', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], name=op.f('fk_hand_wins_hand_id_hands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hand_id', 'winner_seat', name=op.f('pk_hand_wins'))
    )
    op.create_index(op.f('ix_hand_wins_level_rank'), 'hand_wins', ['level_rank'], unique=False)
    op.create_table('hand_yakus',
    sa.Column('hand_id', sa.BigInteger(), nullable=False),
    sa.Column('winner_seat', sa.SmallInteger(), nullable=False),
    sa.Column('yaku', sa.Text(), nullable=False),
    sa.Column('han', sa.SmallInteger(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['hand_id', 'winner_seat'], ['hand_wins.hand_id', 'hand_wins.winner_seat'], name='fk_hand_yakus_hand_wins', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hand_id', 'winner_seat', 'yaku', name=op.f('pk_hand_yakus'))
    )
    op.create_index(op.f('ix_hand_yakus_yaku'), 'hand_yakus', ['yaku'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_hand_yakus_yaku'), table_name='hand_yakus')
    op.drop_table('hand_yakus')
    op.drop_index(op.f('ix_hand_wins_level_rank'), table_name='hand_wins')
    op.drop_table('hand_wins')
    op.drop_table('hand_tenpai')
    op.drop_table('hand_riichi')
    op.drop_index(op.f('ix_match_players_player_id'), table_name='match_players')
    op.drop_table('match_players')
    op.drop_index(op.f('ix_hands_deal_in_seat'), table_name='hands')
    op.drop_table('hands')
    op.drop_index(op.f('ix_adjustments_match_id'), table_name='adjustments')
    op.drop_table('adjustments')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_started_at'), table_name='matches')
    op.drop_index(op.f('ix_matches_max_level_rank'), table_name='matches')
    op.drop_table('matches')
